### PR TITLE
github(summary): add collapsible section for build inputs and bake def

### LINKED ISSUE #369: Optionally use disclosure elements to hide lengthy Docker build summary
When using the `docker/bake-action@v6` action, the resulting build summary are rather long, taking up quite a bit of the vertical space from the rest of the user provide build summaries, requiring much more scroller for readers.

https://github.com/docker/actions-toolkit/blob/7b876a9e9528ce42864ddc1fef9499c2d498b2dc/src/github.ts#L205

While they are nicely detailed for debugging, would it be possible to allow the end user of the resulting docker actions to dynamically configure them to be encapsulate within a togglable disclosure element, via action input?

Even if the just the `<h2>Bake definition</h2>` and `<h2>Build inputs</h2>` sections had their body's nested under a collapsed disclosure element by default, that could be a big gain in reduction of line noise.

Related:
- https://github.com/orgs/community/discussions/44185#discussioncomment-9799051

### PR DESCRIPTION
**Pull request by crazy-max**
fixes #369 

Based on https://github.com/docker/actions-toolkit/actions/runs/9597296326?pr=377#summary-26466096422

Example here: https://github.com/docker/actions-toolkit/actions/runs/9599193396#summary-26472403316

image

image

image

cc @ruffsl @Pesa

### CODE REVIEW

**Comment by dvdksn** [comment]
What do you think about making section titles the `<summary>`? We could make the Preview open by default (`<details open><summary>Preview</summary> ...`). For example:

image

I also noticed that we generate an H1 for every summary. An HTML document should never have more than one H1 so I think we should make them H2.

**Comment by crazy-max** [comment]
@dvdksn PR description updated based on your suggestion

**Review by dvdksn — APPROVED** [review]
Nice, LGTM

**Review by tonistiigi — APPROVED** [review]

**Comment by tonistiigi** [comment]
image

**Pull request merged**
